steps:
  - name: 'node:16-bullseye-slim'
    args:
      - npm
      - exec
      - --
      - esbuild
      - --outdir=.
      - constants.ts
      - index.ts
      - types.ts
    id: 'backend npm exec esbuild'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - gcloud
      - beta
      - functions
      - deploy
      - text-to-speech
      - --gen2
      - --region=us-central1
      - --source=.
      - --runtime=nodejs16
      - --trigger-http
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID
    waitFor: ['backend npm exec esbuild']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - gcloud
      - beta
      - functions
      - deploy
      - oauth2callback
      - --gen2
      - --region=us-central1
      - --source=.
      - --runtime=nodejs16
      - --trigger-http
      - --allow-unauthenticated
    waitFor: ['backend npm exec esbuild']

  - name: 'node:16-bullseye-slim'
    args:
      - npm
      - ci
    waitFor: ['-']
    id: 'frontend npm ci'
  - name: 'node:16-bullseye-slim'
    args:
      - npm
      - run
      - build
    waitFor: ['frontend npm ci']
    id: 'frontend npm run build'
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - deploy
      - --only=hosting
    waitFor: ['frontend npm run build']
