steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - gcloud
      - beta
      - functions
      - deploy
      - text-to-speech
      - --gen2
      - --region=us-central1
      - --source=.
      - --runtime=nodejs16
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=helloHttp
  - name: 'node:16-bullseye-slim'
    args:
      - npm
      - ci
    waitFor: ['-']
  - name: 'node:16-bullseye-slim'
    args:
      - npm
      - run
      - build
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - firebase
      - deploy
      - --only=hosting
