steps:
  - name: 'node:16-bullseye-slim'
    args:
      - npm
      - ci
      - --production
    id: 'backend npm ci'
  - name: 'node:16-bullseye-slim'
    args:
      - npm
      - exec
      - --package=typescript
      - --
      - tsc
      - index.ts
    id: 'backend npm exec tsc'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - gcloud
      - beta
      - functions
      - deploy
      - text-to-speech
      - --gen2
      - --region=us-central1
      - --source=.
      - --runtime=nodejs16
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=helloHttp
    waitFor: ['backend npm exec tsc']

  - name: 'node:16-bullseye-slim'
    args:
      - npm
      - ci
    waitFor: ['-']
    id: 'frontend npm ci'
  - name: 'node:16-bullseye-slim'
    args:
      - npm
      - run
      - build
    waitFor: ['frontend npm ci']
    id: 'frontend npm run build'
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - deploy
      - --only=hosting
    waitFor: ['frontend npm run build']
