steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - "gcloud"
      - "functions"
      - "deploy"
      - "text-to-speech"
      - "--gen2"
      - "--region=us-central1"
      - "--runtime=nodejs18"
      - "--service-account=cloudfunctions@chattalker.iam.gserviceaccount.com"
      - "--set-env-vars=PROJECT_ID=$PROJECT_ID"
      - "--trigger-http"
    waitFor: ["-"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - "gcloud"
      - "functions"
      - "deploy"
      - "youtube-oauth2callback"
      - "--gen2"
      - "--region=us-central1"
      - "--runtime=nodejs18"
      - "--service-account=cloudfunctions@chattalker.iam.gserviceaccount.com"
      - "--set-env-vars=PROJECT_ID=$PROJECT_ID"
      - "--trigger-http"
    waitFor: ["-"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - "gcloud"
      - "functions"
      - "deploy"
      - "youtube-oauth2refresh"
      - "--gen2"
      - "--region=us-central1"
      - "--runtime=nodejs18"
      - "--service-account=cloudfunctions@chattalker.iam.gserviceaccount.com"
      - "--set-env-vars=PROJECT_ID=$PROJECT_ID"
      - "--trigger-http"
    waitFor: ["-"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - "gcloud"
      - "functions"
      - "deploy"
      - "authenticate-with-token"
      - "--gen2"
      - "--region=us-central1"
      - "--runtime=nodejs18"
      - "--service-account=cloudfunctions@chattalker.iam.gserviceaccount.com"
      - "--set-env-vars=PROJECT_ID=$PROJECT_ID"
      - "--trigger-http"
    waitFor: ["-"]

  - name: "node:18-bullseye-slim"
    args:
      - "npm"
      - "ci"
    waitFor: ["-"]
    id: "npm ci"
  - name: "node:18-bullseye-slim"
    args:
      - "npm"
      - "run"
      - "build"
  - name: "gcr.io/$PROJECT_ID/firebase"
    args:
      - "deploy"
      - "--only=hosting"
